title:              Arnav Dhariya
email:              arnavdhariya24@gmail.com
description:        Researcher | Writer | Programmer
author:             Arnav Dhariya
url: "https://arnavdhariya.github.io"
baseurl: ""
phone: "(650) 684-4796"
substack_url: "https://arnavdhariya.substack.com/"

# Social Profiles
github_username:    arnavdhariya
linkedin_username: arnavdhariya

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
